[package]
name = "iseenhorses/classbinder"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
GoodSignal = "stravant/goodsignal@0.3.1"